#Be sure to change volumn location
#start:   docker-compose up -d
#stop:    docker-compse down

services:
    app:
        container_name: demo-app
        image: depaulkenyu/se452-demo-app:latest
        env_file: ./.env
        ports:
            - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
        